### PR TITLE
Removes `Error` by propagating original `Stream/Sink` error

### PR DESCRIPTION
**Pull request by bkchr**
Requires: https://github.com/carllerche/tokio-serde/pull/3

### CODE REVIEW

**Comment by carllerche** [comment]
I restarted CI.

**Comment by carllerche** [comment]
This seems to still be failing :-/

**Comment by bkchr** [comment]
This requires a new release of `tokio_serde`, because it requires the changes of my other pull request.

**Comment by bkchr** [comment]
@carllerche are you willing to release a new version of `tokio_serde`?

**Comment by carllerche** [comment]
Done and restarted CI.

**Comment by bkchr** [comment]
I updated the `Cargo.toml`, now the CI should work :)

**Pull request merged**
